//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Tf2
{
    [Serializable]
    public class LookupTransformActionResultMsg : Message
    {
        public const string k_RosMessageName = "tf2_msgs/LookupTransformActionResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalStatusMsg status;
        public LookupTransformResultMsg result;

        public LookupTransformActionResultMsg()
        {
            this.header = new HeaderMsg();
            this.status = new Actionlib.GoalStatusMsg();
            this.result = new LookupTransformResultMsg();
        }

        public LookupTransformActionResultMsg(HeaderMsg header, Actionlib.GoalStatusMsg status, LookupTransformResultMsg result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }

        public static LookupTransformActionResultMsg Deserialize(MessageDeserializer deserializer) => new LookupTransformActionResultMsg(deserializer);

        private LookupTransformActionResultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.status = Actionlib.GoalStatusMsg.Deserialize(deserializer);
            this.result = LookupTransformResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "LookupTransformActionResultMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
