//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tf2
{
    [Serializable]
    public class LookupTransformActionMsg : Message
    {
        public const string k_RosMessageName = "tf2_msgs/LookupTransformAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public LookupTransformActionGoalMsg action_goal;
        public LookupTransformActionResultMsg action_result;
        public LookupTransformActionFeedbackMsg action_feedback;

        public LookupTransformActionMsg()
        {
            this.action_goal = new LookupTransformActionGoalMsg();
            this.action_result = new LookupTransformActionResultMsg();
            this.action_feedback = new LookupTransformActionFeedbackMsg();
        }

        public LookupTransformActionMsg(LookupTransformActionGoalMsg action_goal, LookupTransformActionResultMsg action_result, LookupTransformActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static LookupTransformActionMsg Deserialize(MessageDeserializer deserializer) => new LookupTransformActionMsg(deserializer);

        private LookupTransformActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = LookupTransformActionGoalMsg.Deserialize(deserializer);
            this.action_result = LookupTransformActionResultMsg.Deserialize(deserializer);
            this.action_feedback = LookupTransformActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "LookupTransformActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
